/*
 * Filter Coefficients (C Source) generated by the Filter Design and Analysis Tool
 * Generated by MATLAB(R) 24.2 and Signal Processing Toolbox 24.2.
 * Generated on: 28-Feb-2026 09:41:36
 */

/*
 * 离散时间 FIR 滤波器(实数)
 * ----------------
 * 滤波器结构  : 直接型 FIR
 * 滤波器长度  : 51
 * 稳定     : 是
 * 线性相位   : 是 (Type 1)
 */

/* General type conversion for MATLAB generated C-code  */
#include "tmwtypes.h"
/* 
 * Expected path to tmwtypes.h 
 * D:\extern\include\tmwtypes.h 
 */
/*
 * Warning - Filter coefficients were truncated to fit specified data type.  
 *   The resulting response may not match generated theoretical response.
 *   Use the Filter Design & Analysis Tool to design accurate
 *   single-precision filter coefficients.
 */
const int BL = 51;
const real32_T B[51] = {
   0.002915534889, 0.003051500069,  0.00345056993, 0.004107376561, 0.005012389738,
   0.006152060814, 0.007509032264, 0.009062412195,   0.0107881017,  0.01265918091,
    0.01464633644,  0.01671833172,  0.01884250715,  0.02098530531,  0.02311281115,
    0.02519129775,  0.02718777396,  0.02907051146,  0.03080956079,  0.03237723932,
     0.0337485671,  0.03490169346,  0.03581822291,  0.03648354113,   0.0368870236,
    0.03702224046,   0.0368870236,  0.03648354113,  0.03581822291,  0.03490169346,
     0.0337485671,  0.03237723932,  0.03080956079,  0.02907051146,  0.02718777396,
    0.02519129775,  0.02311281115,  0.02098530531,  0.01884250715,  0.01671833172,
    0.01464633644,  0.01265918091,   0.0107881017, 0.009062412195, 0.007509032264,
   0.006152060814, 0.005012389738, 0.004107376561,  0.00345056993, 0.003051500069,
   0.002915534889
};
